# Generated by Django 3.2.20 on 2023-07-23 14:12

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=300), size=None),
        ),
    ]
