# Generated by Django 3.2.20 on 2023-07-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_instructions_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.recipe')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.instruction')),
            ],
            options={
                'ordering': ('step', 'order'),
            },
        ),
    ]
