# Generated by Django 3.2.20 on 2023-07-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_instructionthroughmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='blog.recipe'),
        ),
        migrations.DeleteModel(
            name='InstructionThroughModel',
        ),
    ]
