# Generated by Django 3.2.20 on 2023-07-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230724_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='step',
            new_name='steps',
        ),
    ]
